import { useState } from 'react';
import { Sparkles, AlertCircle, Brain, Heart, Zap, LineChart, List, Check } from 'lucide-react';
import { Doughnut } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { generateWeeklyReport } from '../services/gemini';
import { getRecentMoods, getJournals, getBurnoutResults, getScenarioInteractions } from '../services/storage';
import { useToast } from '../components/Toast';

ChartJS.register(ArcElement, Tooltip, Legend);

const MOOD_COLORS = {
  Stressed: '#d47e75', Anxious: '#e6b72e', Sad: '#769a62',
  Confused: '#9b8a79', Bored: '#c48364', Neutral: '#629c51',
};

export default function Report() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const addToast = useToast();

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = {
        moods: getRecentMoods(30),
        journals: getJournals().slice(0, 10),
        burnout: getBurnoutResults(),
        scenarios: getScenarioInteractions(),
      };
      const result = await generateWeeklyReport(data);
      setReport(result);
      addToast('Weekly report generated by Gemini', 'info');
    } catch (err) {
      if (err.message === 'NO_API_KEY') {
        setError('Please set your OpenRouter API key in the .env file (VITE_OPENROUTER_API_KEY)');
      } else {
        setError('Report generation failed. Please try again.');
      }
    }
    setLoading(false);
  };

  const chartData = report?.mood_distribution ? {
    labels: Object.keys(report.mood_distribution),
    datasets: [{
      data: Object.values(report.mood_distribution),
      backgroundColor: Object.keys(report.mood_distribution).map(m => MOOD_COLORS[m] || '#94a3b8'),
      borderWidth: 0,
      hoverOffset: 4,
    }],
  } : null;

  const chartOptions = {
    responsive: true,
    plugins: {
      legend: { position: 'bottom', labels: { padding: 20, usePointStyle: true, font: { family: 'Inter', size: 12 } } },
    },
    cutout: '65%',
  };

  return (
    <div className="report-page-bg fade-in" style={{ paddingBottom: 100 }}>
      {/* Top Header matching reference */}
      <div style={{ padding: '30px 6%', position: 'relative', zIndex: 10 }}>
        <h1 style={{ fontSize: '1.8rem', color: '#3a4436', fontWeight: 500, display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
          <LineChart size={28} color="#429f5f" strokeWidth={2.5} /> Weekly Report
        </h1>
        <p style={{ color: '#889886', fontSize: '1rem' }}>
          Gemini AI generates a comprehensive mental health summary from your data.
        </p>
      </div>

      <div className="report-hero-container">
        {!report && !loading && (
          <div className="report-glass-card fade-in">
            
            <div className="report-icon-ring">
              <svg className="progress-svg">
                <circle className="bg-ring" cx="55" cy="55" r="50" />
                <circle className="progress-ring" cx="55" cy="55" r="50" />
              </svg>
              <LineChart className="report-icon-inner" size={38} strokeWidth={2.5} />
            </div>

            <h2 style={{ fontSize: '1.6rem', color: '#2d3329', fontWeight: 600, marginBottom: 12 }}>
              Generate Your Report
            </h2>
            <p style={{ color: '#889886', fontSize: '1rem', lineHeight: 1.6, maxWidth: 360, margin: '0 auto' }}>
              Gemini AI will analyze your mood logs, journal entries, and assessments to create a personalized wellness report.
            </p>

            <div className="report-sources-row">
              <div className="report-source-pill">
                <div style={{ width: 10, height: 10, borderRadius: '50%', border: '2px solid #5a8a5b' }} /> Mood Logs
              </div>
              <div className="report-source-pill">
                <List size={16} color="#5a8a5b" /> Journal
              </div>
              <div className="report-source-pill">
                <Check size={16} color="#5a8a5b" /> Assessments
              </div>
            </div>

            {error && <div className="error-banner" style={{ marginBottom: 16 }}><AlertCircle size={16} />{error}</div>}
            
            <button className="report-generate-btn" onClick={handleGenerate}>
              Generate with Gemini
            </button>
            
            <div className="report-footer-text">
              <div className="report-footer-dot" /> Powered by Gemini AI · End-to-end encrypted
            </div>
            
          </div>
        )}

        {loading && (
          <div className="report-glass-card fade-in" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <div className="report-icon-ring" style={{ animation: 'spin 2s linear infinite' }}>
              <svg className="progress-svg">
                <circle className="bg-ring" cx="55" cy="55" r="50" />
                <circle className="progress-ring" cx="55" cy="55" r="50" strokeDashoffset="120" />
              </svg>
              <Sparkles className="report-icon-inner" size={38} />
            </div>
            <h2 style={{ fontSize: '1.4rem', color: '#2d3329', marginBottom: 16 }}>Analyzing your week</h2>
            <div className="analyzing-dots"><span /><span /><span /></div>
          </div>
        )}
      </div>

      {report && !loading && (
        <div className="fade-in" style={{ padding: '0 6%', maxWidth: 800, margin: '0 auto', position: 'relative', zIndex: 10 }}>
          {/* Summary Stats */}
          <div className="report-summary-grid">
            <div className="report-stat stat-wellness">
              <div className="report-stat-value" style={{ color: report.wellness_score >= 70 ? 'var(--green-500)' : report.wellness_score >= 40 ? 'var(--amber-500)' : 'var(--rose-500)' }}>
                {report.wellness_score}
              </div>
              <div className="report-stat-label">Wellness Score</div>
            </div>
            <div className="report-stat stat-mood">
              <div className="report-stat-value" style={{ fontSize: '1.2rem' }}>{report.dominant_mood}</div>
              <div className="report-stat-label">Dominant Mood</div>
            </div>
            <div className="report-stat stat-stress">
              <div className="report-stat-value" style={{ fontSize: '1rem' }}>{report.main_stress_trigger}</div>
              <div className="report-stat-label">Stress Trigger</div>
            </div>
            {report.total_entries && (
              <div className="report-stat stat-entries">
                <div className="report-stat-value">{report.total_entries.moods + report.total_entries.journals}</div>
                <div className="report-stat-label">Total Entries</div>
              </div>
            )}
          </div>

          <div className="grid-2">
            {/* Chart */}
            {chartData && (
              <div className="card glass-card">
                <div className="card-title" style={{ marginBottom: 16 }}>Mood Distribution</div>
                <div style={{ maxWidth: 280, margin: '0 auto' }}>
                  <Doughnut data={chartData} options={chartOptions} />
                </div>
              </div>
            )}

            {/* AI Insight */}
            <div className="card glass-card">
              <div className="card-title" style={{ marginBottom: 16 }}>
                <Brain size={16} style={{ marginRight: 8, verticalAlign: -2 }} />
                Gemini AI Insight
              </div>
              <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 20, borderLeft: '3px solid var(--accent-400)', paddingLeft: 16 }}>
                {report.weekly_insight}
              </p>

              {report.positive_behaviors?.length > 0 && (
                <div style={{ marginBottom: 16 }}>
                  <div className="ai-result-label" style={{ marginBottom: 8 }}>🌟 Positive Behaviors</div>
                  {report.positive_behaviors.map((b, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 6, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                      <Heart size={14} style={{ color: 'var(--green-500)', flexShrink: 0, marginTop: 2 }} />{b}
                    </div>
                  ))}
                </div>
              )}

              {report.recommendations?.length > 0 && (
                <div>
                  <div className="ai-result-label" style={{ marginBottom: 8 }}>💡 Recommendations</div>
                  {report.recommendations.map((r, i) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, marginBottom: 6, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                      <Zap size={14} style={{ color: 'var(--accent-500)', flexShrink: 0, marginTop: 2 }} />{r}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          <div style={{ marginTop: 20, textAlign: 'center' }}>
            <button className="btn btn-ghost" onClick={() => { setReport(null); setError(null); }}>Generate New Report</button>
          </div>
        </div>
      )}
    </div>
  );
}
